don’t install RDMA/libibverbs
sometimes fails with

 'Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper
Examining rdma-6.9_4.1-3.el6.noarch.rpm: rdma-6.9_4.1-3.el6.noarch
rdma-6.9_4.1-3.el6.noarch.rpm: does not update installed package.
Error: Nothing to do
'